export const DEFAULT_PARTNER_ID = '1';
export const DEFAULT_CUSTOMER_ID = 'u-customer-1';

export const seedData = {
  suggestedPrompts: [
    'Find vet near me',
    'Book electrician',
    'Home cleaning tomorrow',
    'Emergency plumber',
    'AC repair service',
    'Carpenter for furniture',
  ],
  servicePartners: [
    {
      id: '1',
      name: 'Dr. Sarah Veterinary Clinic',
      category: 'Veterinary',
      rating: 4.8,
      reviewCount: 234,
      distance: 1.2,
      eta: 15,
      priceRange: 'INR 500-2000',
      available: true,
      image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop',
      phone: '+91 9000000001',
      expertise: ['Pet Care', 'Emergency Care', 'Vaccination', 'Surgery'],
      description: 'Expert veterinary care for pets with 15+ years of experience.',
      verified: true,
      services: [
        { id: 's1', name: 'General Checkup', price: 500, duration: 30, description: 'Complete health examination' },
        { id: 's2', name: 'Vaccination', price: 800, duration: 20, description: 'Annual vaccination shots' },
        { id: 's3', name: 'Emergency Care', price: 2000, duration: 60, description: 'Urgent emergency service' },
      ],
      availability: [
        { date: '2026-04-04', slots: ['09:00', '10:00', '11:00', '14:00', '15:00', '16:00'] },
        { date: '2026-04-05', slots: ['09:00', '10:00', '11:00', '14:00', '15:00'] },
        { date: '2026-04-06', slots: ['09:00', '11:00', '14:00', '16:00'] },
      ],
    },
    {
      id: '2',
      name: 'PowerFix Electricians',
      category: 'Electrician',
      rating: 4.6,
      reviewCount: 189,
      distance: 0.8,
      eta: 10,
      priceRange: 'INR 300-1500',
      available: true,
      image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&h=400&fit=crop',
      phone: '+91 9000000002',
      expertise: ['Wiring', 'Repairs', 'Installation', 'Emergency'],
      description: 'Licensed electricians for home and office electrical needs.',
      verified: true,
      services: [
        { id: 's4', name: 'Fan Installation', price: 300, duration: 45, description: 'Install ceiling fan' },
        { id: 's5', name: 'Wiring Repair', price: 800, duration: 90, description: 'Fix wiring issues' },
        { id: 's6', name: 'Switch Replacement', price: 200, duration: 30, description: 'Replace faulty switches' },
      ],
      availability: [
        { date: '2026-04-04', slots: ['08:00', '09:00', '10:00', '14:00', '15:00', '17:00'] },
        { date: '2026-04-05', slots: ['08:00', '09:00', '11:00', '15:00', '17:00'] },
      ],
    },
    {
      id: '3',
      name: 'QuickFix Plumbing',
      category: 'Plumber',
      rating: 4.7,
      reviewCount: 312,
      distance: 2.0,
      eta: 20,
      priceRange: 'INR 400-2000',
      available: true,
      image: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400&h=400&fit=crop',
      phone: '+91 9000000003',
      expertise: ['Pipe Repair', 'Leak Fix', 'Bathroom', 'Kitchen'],
      description: 'Trusted plumbing experts available for emergency support.',
      verified: true,
      services: [
        { id: 's7', name: 'Leak Repair', price: 500, duration: 60, description: 'Fix pipe or tap leaks' },
        { id: 's8', name: 'Drain Cleaning', price: 700, duration: 45, description: 'Unblock drainage lines' },
        { id: 's9', name: 'Tap Installation', price: 400, duration: 30, description: 'Install or replace taps' },
      ],
      availability: [
        { date: '2026-04-04', slots: ['09:00', '10:00', '14:00', '16:00'] },
        { date: '2026-04-05', slots: ['08:00', '10:00', '11:00', '15:00'] },
      ],
    },
    {
      id: '4',
      name: 'Sparkle Home Cleaning',
      category: 'Home Cleaning',
      rating: 4.9,
      reviewCount: 456,
      distance: 1.5,
      eta: 18,
      priceRange: 'INR 800-3000',
      available: false,
      image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=400&fit=crop',
      phone: '+91 9000000004',
      expertise: ['Deep Cleaning', 'Regular Cleaning', 'Kitchen', 'Bathroom'],
      description: 'Professional home cleaning with eco-friendly products.',
      verified: true,
      services: [
        { id: 's10', name: 'Regular Cleaning', price: 800, duration: 120, description: 'Complete home cleaning' },
        { id: 's11', name: 'Deep Cleaning', price: 2500, duration: 240, description: 'Intensive deep cleaning' },
        { id: 's12', name: 'Kitchen Cleaning', price: 1200, duration: 90, description: 'Detailed kitchen cleaning' },
      ],
      availability: [
        { date: '2026-04-05', slots: ['09:00', '14:00'] },
        { date: '2026-04-06', slots: ['09:00', '10:00', '14:00'] },
      ],
    },
    {
      id: '5',
      name: 'AC Care Experts',
      category: 'AC Repair',
      rating: 4.5,
      reviewCount: 178,
      distance: 3.2,
      eta: 30,
      priceRange: 'INR 500-2500',
      available: true,
      image: 'https://images.unsplash.com/photo-1631545806609-6b3c0f4e8ec6?w=400&h=400&fit=crop',
      phone: '+91 9000000005',
      expertise: ['AC Service', 'Repair', 'Installation', 'Gas Refill'],
      description: 'Certified AC technicians for all major brands.',
      verified: true,
      services: [
        { id: 's13', name: 'AC Service', price: 500, duration: 60, description: 'Regular AC maintenance' },
        { id: 's14', name: 'Gas Refill', price: 1800, duration: 45, description: 'AC gas refill' },
        { id: 's15', name: 'AC Repair', price: 1200, duration: 90, description: 'Repair and diagnostics' },
      ],
      availability: [
        { date: '2026-04-04', slots: ['10:00', '14:00', '16:00'] },
        { date: '2026-04-05', slots: ['09:00', '11:00', '15:00'] },
      ],
    },
  ],
  reviews: [
    {
      id: 'r1',
      partnerId: '1',
      userId: 'u-customer-1',
      userName: 'Rahul Sharma',
      userImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
      rating: 5,
      comment: 'Excellent service, very professional and punctual.',
      tags: ['Professional', 'On Time', 'Friendly'],
      date: '2026-03-28',
      photos: ['https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=300&h=300&fit=crop'],
    },
    {
      id: 'r2',
      partnerId: '2',
      userId: 'u-customer-2',
      userName: 'Priya Patel',
      userImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
      rating: 5,
      comment: 'Fixed the wiring issue quickly and efficiently.',
      tags: ['Quick Service', 'Expert', 'Value for Money'],
      date: '2026-03-25',
    },
    {
      id: 'r3',
      partnerId: '1',
      userId: 'u-customer-3',
      userName: 'Amit Kumar',
      userImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
      rating: 4,
      comment: 'Good service overall and polite communication.',
      tags: ['Good Quality', 'Polite'],
      date: '2026-03-20',
    },
  ],
  bookings: [
    {
      id: 'b1',
      customerId: 'u-customer-1',
      partnerId: '1',
      partnerName: 'Dr. Sarah Veterinary Clinic',
      partnerImage: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop',
      serviceId: 's1',
      service: 'General Checkup',
      date: '2026-04-04',
      time: '10:00',
      status: 'assigned',
      paymentStatus: 'paid',
      paymentMethod: 'upi',
      price: 550,
      address: '123 MG Road, Bangalore',
      notes: '',
      category: 'Veterinary',
      jobId: 'j1',
    },
    {
      id: 'b2',
      customerId: 'u-customer-1',
      partnerId: '2',
      partnerName: 'PowerFix Electricians',
      partnerImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&h=400&fit=crop',
      serviceId: 's4',
      service: 'Fan Installation',
      date: '2026-04-05',
      time: '14:00',
      status: 'pending',
      paymentStatus: 'pending',
      paymentMethod: '',
      price: 350,
      address: '123 MG Road, Bangalore',
      notes: '',
      category: 'Electrician',
      jobId: '',
    },
    {
      id: 'b3',
      customerId: 'u-customer-1',
      partnerId: '4',
      partnerName: 'Sparkle Home Cleaning',
      partnerImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=400&fit=crop',
      serviceId: 's11',
      service: 'Deep Cleaning',
      date: '2026-03-30',
      time: '09:00',
      status: 'completed',
      paymentStatus: 'paid',
      paymentMethod: 'card',
      price: 2550,
      address: '123 MG Road, Bangalore',
      notes: '',
      category: 'Home Cleaning',
      jobId: 'j3',
    },
  ],
  jobs: [
    {
      id: 'j1',
      bookingId: 'b1',
      partnerId: '1',
      customerId: 'u-customer-1',
      customerName: 'Rahul Sharma',
      customerImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
      service: 'General Checkup',
      date: '2026-04-04',
      time: '10:00',
      status: 'accepted',
      price: 500,
      address: '123 MG Road, Bangalore',
      distance: 1.2,
    },
    {
      id: 'j2',
      bookingId: '',
      partnerId: '1',
      customerId: 'u-customer-2',
      customerName: 'Priya Patel',
      customerImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
      service: 'Vaccination',
      date: '2026-04-04',
      time: '14:00',
      status: 'pending',
      price: 800,
      address: '456 Indiranagar, Bangalore',
      distance: 2.5,
    },
    {
      id: 'j3',
      bookingId: 'b3',
      partnerId: '1',
      customerId: 'u-customer-3',
      customerName: 'Amit Kumar',
      customerImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
      service: 'Emergency Care',
      date: '2026-04-03',
      time: '16:00',
      status: 'completed',
      price: 2000,
      address: '789 Koramangala, Bangalore',
      distance: 0.8,
    },
  ],
  partnerAvailabilityByPartnerId: {
    '1': {
      Monday: { enabled: true, slots: ['09:00', '10:00', '11:00', '14:00', '15:00', '16:00'] },
      Tuesday: { enabled: true, slots: ['09:00', '10:00', '11:00', '14:00', '15:00'] },
      Wednesday: { enabled: true, slots: ['09:00', '11:00', '14:00', '16:00'] },
      Thursday: { enabled: true, slots: ['09:00', '10:00', '14:00', '15:00', '16:00'] },
      Friday: { enabled: true, slots: ['09:00', '10:00', '11:00', '15:00', '16:00'] },
      Saturday: { enabled: false, slots: [] },
      Sunday: { enabled: false, slots: [] },
    },
  },
  transactions: [
    {
      id: 't1',
      partnerId: '1',
      bookingId: 'b1',
      customer: 'Rahul Sharma',
      service: 'General Checkup',
      amount: 500,
      date: '2026-04-03',
      status: 'completed',
    },
    {
      id: 't2',
      partnerId: '1',
      bookingId: '',
      customer: 'Priya Patel',
      service: 'Vaccination',
      amount: 800,
      date: '2026-04-03',
      status: 'completed',
    },
    {
      id: 't3',
      partnerId: '1',
      bookingId: 'b3',
      customer: 'Amit Kumar',
      service: 'Emergency Care',
      amount: 2000,
      date: '2026-04-02',
      status: 'completed',
    },
    {
      id: 't4',
      partnerId: '1',
      bookingId: '',
      customer: 'Sneha Singh',
      service: 'General Checkup',
      amount: 500,
      date: '2026-04-02',
      status: 'completed',
    },
    {
      id: 't5',
      partnerId: '1',
      bookingId: '',
      customer: 'Ravi Verma',
      service: 'Vaccination',
      amount: 800,
      date: '2026-04-01',
      status: 'pending',
    },
  ],
  users: [
    {
      id: 'u-customer-1',
      name: 'Rahul Sharma',
      role: 'customer',
      marketplaceRole: 'client',
      phone: '9876543210',
      email: 'rahul.sharma@example.com',
      ratings: 4.7,
      walletBalance: 3250,
      location: 'Bangalore',
      skills: ['Client Management', 'Planning'],
    },
    {
      id: 'u-partner-1',
      name: 'Dr. Sarah Veterinary Clinic',
      role: 'partner',
      marketplaceRole: 'worker',
      phone: '9000000001',
      email: 'partner1@example.com',
      partnerId: '1',
      ratings: 4.9,
      walletBalance: 18900,
      location: 'Bangalore',
      skills: ['Veterinary', 'Emergency Care', 'Pet Grooming'],
    },
  ],
  marketplaceJobs: [
    {
      job_id: 'mj-1',
      owner_id: 'u-customer-1',
      title: 'Need React landing page designer',
      description: 'Design and implement a responsive landing page for our startup.',
      budget: 12000,
      location: 'Remote',
      mode: 'online',
      status: 'open',
      requiredSkills: ['React', 'UI/UX', 'Tailwind'],
      attachments: [],
      createdAt: '2026-04-04T10:00:00.000Z',
      applicationsCount: 1,
      selectedApplicantId: '',
    },
    {
      job_id: 'mj-2',
      owner_id: 'u-customer-1',
      title: 'Electrician for office wiring check',
      description: 'Need on-site inspection and minor repairs in Koramangala office.',
      budget: 3500,
      location: 'Bangalore',
      mode: 'offline',
      status: 'ongoing',
      requiredSkills: ['Electrical', 'Troubleshooting'],
      attachments: [],
      createdAt: '2026-04-03T08:00:00.000Z',
      applicationsCount: 1,
      selectedApplicantId: 'u-partner-1',
    },
    {
      job_id: 'mj-3',
      owner_id: 'u-customer-1',
      title: 'Logo and brand guideline',
      description: 'Create professional logo variations and brand color guide.',
      budget: 8000,
      location: 'Remote',
      mode: 'online',
      status: 'completed',
      requiredSkills: ['Branding', 'Illustrator'],
      attachments: [],
      createdAt: '2026-04-01T07:30:00.000Z',
      applicationsCount: 1,
      selectedApplicantId: 'u-partner-1',
    },
  ],
  marketplaceApplications: [
    {
      application_id: 'ma-1',
      applicant_id: 'u-partner-1',
      job_id: 'mj-1',
      proposal: 'I can deliver this in 3 days with 2 revision rounds.',
      status: 'pending',
      createdAt: '2026-04-04T12:00:00.000Z',
    },
    {
      application_id: 'ma-2',
      applicant_id: 'u-partner-1',
      job_id: 'mj-2',
      proposal: 'Available today evening, can complete within 2 hours.',
      status: 'accepted',
      createdAt: '2026-04-03T09:15:00.000Z',
    },
    {
      application_id: 'ma-3',
      applicant_id: 'u-partner-1',
      job_id: 'mj-3',
      proposal: 'Sharing 3 concepts and final exports.',
      status: 'accepted',
      createdAt: '2026-04-01T08:10:00.000Z',
    },
  ],
  marketplaceMessages: [
    {
      message_id: 'mm-1',
      sender_id: 'u-customer-1',
      receiver_id: 'u-partner-1',
      message: 'Can you share your portfolio links?',
      timestamp: '2026-04-04T12:30:00.000Z',
      job_id: 'mj-1',
    },
    {
      message_id: 'mm-2',
      sender_id: 'u-partner-1',
      receiver_id: 'u-customer-1',
      message: 'Sure, sharing now. Also available for call.',
      timestamp: '2026-04-04T12:35:00.000Z',
      job_id: 'mj-1',
    },
  ],
  marketplaceNotifications: [
    {
      notification_id: 'mn-1',
      user_id: 'u-customer-1',
      title: 'New application received',
      body: 'Dr. Sarah Veterinary Clinic applied to "Need React landing page designer".',
      type: 'application',
      isRead: false,
      createdAt: '2026-04-04T12:00:00.000Z',
    },
    {
      notification_id: 'mn-2',
      user_id: 'u-partner-1',
      title: 'Application accepted',
      body: 'Your application was accepted for "Electrician for office wiring check".',
      type: 'application',
      isRead: false,
      createdAt: '2026-04-03T09:30:00.000Z',
    },
  ],
  clickLogs: [],
  authRequests: {},
  sessions: [],
};
